In [ ]:
import numpy as np
import cv2
from sklearn.datasets import fetch_lfw_people
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Load the LFW dataset
lfw_dataset = fetch_lfw_people(min_faces_per_person=50, resize=0.4)
X = lfw_dataset.data
y = lfw_dataset.target
target_names = lfw_dataset.target_names
print(X)
print("______________________")
print(y)
print("______________________")
print(target_names)


[[0.31764707 0.35555556 0.45228758 ... 0.42222223 0.5921569  0.49019608]
 [0.1385621  0.27320263 0.33464053 ... 0.23529412 0.3267974  0.45490196]
 [0.33594772 0.21830066 0.22745098 ... 0.6928105  0.32156864 0.303268  ]
 ...
 [0.19346406 0.24705882 0.34248367 ... 0.7346406  0.6640523  0.6117647 ]
 [0.530719   0.62614375 0.6653595  ... 0.9163399  0.8928105  0.8862745 ]
 [0.11633987 0.10196079 0.1267974  ... 0.13333334 0.13725491 0.2535948 ]]
______________________
[11  4  2 ...  3 11  5]
______________________
['Ariel Sharon' 'Colin Powell' 'Donald Rumsfeld' 'George W Bush'
 'Gerhard Schroeder' 'Hugo Chavez' 'Jacques Chirac' 'Jean Chretien'
 'John Ashcroft' 'Junichiro Koizumi' 'Serena Williams' 'Tony Blair']


In [ ]:
# Preprocess the images
X = X.reshape((X.shape[0], 50, 37))  # Reshape to (num_samples, height, width)
print("before:---------------")
print(X)
X = np.array([cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX) for img in X])  # Normalize pixel values
print("after:------------------------")
print(X)
print(X.shape)

before:---------------
[[[0.31764707 0.35555556 0.45228758 ... 0.20522876 0.24444444 0.30588236]
  [0.34640524 0.3764706  0.39869282 ... 0.18954249 0.17777778 0.27973858]
  [0.36601308 0.37254903 0.3254902  ... 0.24183007 0.17908497 0.21960784]
  ...
  [0.19084968 0.18300654 0.17908497 ... 0.7241831  0.5124183  0.3281046 ]
  [0.1882353  0.18431373 0.18039216 ... 0.6013072  0.5633987  0.38039216]
  [0.18692811 0.18562092 0.18039216 ... 0.42222223 0.5921569  0.49019608]]

 [[0.1385621  0.27320263 0.33464053 ... 0.24705882 0.16993465 0.1633987 ]
  [0.1764706  0.3137255  0.33464053 ... 0.30849674 0.22091503 0.20653595]
  [0.20784314 0.3281046  0.33071896 ... 0.36732027 0.24183007 0.22091503]
  ...
  [0.02745098 0.23137255 0.53464055 ... 0.8718955  0.8156863  0.7764706 ]
  [0.02614379 0.24183007 0.54640526 ... 0.4640523  0.475817   0.48235297]
  [0.02091503 0.2535948  0.54901963 ... 0.23529412 0.3267974  0.45490196]]

 [[0.33594772 0.21830066 0.22745098 ... 0.39346406 0.37908497 0.38169935]

In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Encode labels
print(len(y_train))
print(len(y_test))
print(f"Original unique labels: {np.unique(y_train)}")

le = LabelEncoder()
y_train = le.fit_transform(y_train)
print("after---------------------")
# print(y_train)
y_test = le.transform(y_test)
print(y_test)
print(f"Original unique labels: {np.unique(y_train)}")
print(len(y_train))
print(len(y_test))

1248
312
Original unique labels: [ 0  1  2  3  4  5  6  7  8  9 10 11]
after---------------------
[ 3  1  3 11  1  3  5  2  4  2  5  2 11  0  3  3  1  1  0  5  3  3  3 10
 11  3  3  8  1  1  2  6  3  2  3  3  9  3 10  3  0  1  1 11  5  3  3  3
  3  3  1  3  8  1  3  4  1  1  8  2  7  3  3  9  4  1  2  2  3  3  3 11
  5  3  1  3  3  8  4  2  4  3  2  4  1 11  1 11 11  1  3  3  1 11 11 11
  2  4  3  3  4  5  2  3  3  3  9  2  4  3  1  0  3  3  3  3  1 10  4  4
  1  7  0  1 11  3 10 10  3  3  1  6  7 11  7 11  1 11  3  5  3  3  6  3
  1  7  1  9  5  3  5  7  4  3  8  1  3  2 11  1  9  3  1  3 11  1  3 11
  3  2  3  3  3 11  3  1 11  8  1  3  2  3  3  1  8  0 11 11  1  5  7  3
  3 11  1  1  4  8  3  1  3  3  3  3  2  3  2  3  2  3 11  2  3  3  3 11
 11  5  5  4  3  3  0  3  3 11  1  3  8  2  3  7  8  3  3 11  1  3  9  6
  3  7  1  4  3  2  1 11  3  5  1  4  4  1  3  1  2  1  2  4  6  1  1  1
  8  3 11  6  3  3  1  3  1  6  3  0  3  7  0  1  3  7  8 11  3  1  4  4
  3 10 11  5  3  3  1  9  

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization

def create_cnn_model(input_shape):
    model = Sequential()
    model.add(Conv2D(32, (3, 3), activation='relu', input_shape=input_shape))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(len(target_names), activation='softmax'))

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

cnn_model = create_cnn_model((50, 37, 1))


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
def create_cnn_model_two(input_shape):
    model = Sequential()

    # Convolutional Block 1
    model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=input_shape))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # Convolutional Block 2
    model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # Convolutional Block 3
    model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # Additional Convolutional Block 4, with padding and smaller kernel size
    model.add(Conv2D(256, (2, 2), activation='relu', padding='same'))
    model.add(BatchNormalization())  # Batch normalization
    model.add(MaxPooling2D(pool_size=(2, 2), padding='same'))

    # Flatten and Dense Layers
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(len(target_names), activation='softmax'))

    # Compile the model
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

cnn_model_two = create_cnn_model_two((50, 37, 1))


In [ ]:
def create_cnn_model_three(input_shape):
    model = Sequential()

    # First convolutional block
    model.add(Conv2D(32, (3, 3), activation='relu', input_shape=input_shape))
    model.add(Conv2D(32, (3, 3), activation='relu'))  # Added another Conv2D layer
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # Second convolutional block
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(Conv2D(64, (3, 3), activation='relu'))  # Added another Conv2D layer
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # Third convolutional block
    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(Conv2D(128, (3, 3), activation='relu'))  # Added another Conv2D layer
    model.add(MaxPooling2D(pool_size=(2, 2)))

    # Fourth convolutional block
    model.add(Conv2D(256, (1, 1), activation='relu'))
    model.add(Conv2D(256, (1, 1), activation='relu'))  # Added another Conv2D layer
    # model.add(MaxPooling2D(pool_size=(2, 2)))

    # Flatten the output from the convolutional blocks
    model.add(Flatten())

    # Fully connected layers
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(len(target_names), activation='softmax'))

    # Compile the model
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

cnn_model_three = create_cnn_model_three((50, 37, 1))


In [ ]:
# Reshape data for CNN input
X_train_cnn = X_train.reshape((X_train.shape[0], 50, 37, 1))
X_test_cnn = X_test.reshape((X_test.shape[0], 50, 37, 1))

# Train the model
cnn_model.fit(X_train_cnn, y_train, epochs=20, batch_size=32, validation_split=0.1)


Epoch 1/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 10s 189ms/step - accuracy: 0.1972 - loss: 7.0414 - val_accuracy: 0.3520 - val_loss: 2.0868
Epoch 2/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 6s 69ms/step - accuracy: 0.2938 - loss: 2.2264 - val_accuracy: 0.3920 - val_loss: 1.9966
Epoch 3/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 3s 70ms/step - accuracy: 0.3438 - loss: 2.0394 - val_accuracy: 0.3680 - val_loss: 1.8203
Epoch 4/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 6s 98ms/step - accuracy: 0.3719 - loss: 1.9574 - val_accuracy: 0.4240 - val_loss: 1.6634
Epoch 5/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.4306 - loss: 1.8209 - val_accuracy: 0.5040 - val_loss: 1.5613
Epoch 6/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 3s 69ms/step - accuracy: 0.4162 - loss: 1.7952 - val_accuracy: 0.4960 - val_loss: 1.5614
Epoch 7/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 3s 70ms/step - accuracy: 0.4988 - loss: 1.6347 - val_accuracy: 0.6640 - val_loss: 1.2223
Epoch 8/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - accuracy: 0.5433 - loss: 1.4146 - val_accuracy: 0.6880 -

In [ ]:
# Train the model
cnn_model_two.fit(X_train_cnn, y_train, epochs=20, batch_size=32, validation_split=0.1)

Epoch 1/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 9s 170ms/step - accuracy: 0.2585 - loss: 2.8671 - val_accuracy: 0.3520 - val_loss: 3.6921
Epoch 2/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 9s 135ms/step - accuracy: 0.2927 - loss: 2.2176 - val_accuracy: 0.3520 - val_loss: 3.7951
Epoch 3/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 6s 155ms/step - accuracy: 0.3029 - loss: 2.2330 - val_accuracy: 0.3520 - val_loss: 2.2168
Epoch 4/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 10s 153ms/step - accuracy: 0.3730 - loss: 2.1175 - val_accuracy: 0.3200 - val_loss: 2.0788
Epoch 5/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 9s 122ms/step - accuracy: 0.3740 - loss: 2.0554 - val_accuracy: 0.3840 - val_loss: 2.0501
Epoch 6/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 7s 173ms/step - accuracy: 0.3583 - loss: 2.0965 - val_accuracy: 0.3360 - val_loss: 4.0963
Epoch 7/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 8s 122ms/step - accuracy: 0.3833 - loss: 2.0794 - val_accuracy: 0.1600 - val_loss: 5.3957
Epoch 8/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 7s 163ms/step - accuracy: 0.3852 - loss: 2.0358 - val_accuracy: 0

In [ ]:
# Train the model
cnn_model_three.fit(X_train_cnn, y_train, epochs=20, batch_size=32, validation_split=0.1)

Epoch 1/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 10s 184ms/step - accuracy: 0.2685 - loss: 2.5305 - val_accuracy: 0.3520 - val_loss: 2.0774
Epoch 2/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 10s 181ms/step - accuracy: 0.3596 - loss: 2.0762 - val_accuracy: 0.3520 - val_loss: 1.9167
Epoch 3/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 8s 228ms/step - accuracy: 0.3694 - loss: 1.9597 - val_accuracy: 0.4240 - val_loss: 1.8049
Epoch 4/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 9s 181ms/step - accuracy: 0.4437 - loss: 1.7550 - val_accuracy: 0.4640 - val_loss: 1.7449
Epoch 5/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 10s 176ms/step - accuracy: 0.4495 - loss: 1.6494 - val_accuracy: 0.5680 - val_loss: 1.3112
Epoch 6/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 8s 222ms/step - accuracy: 0.5186 - loss: 1.4732 - val_accuracy: 0.6000 - val_loss: 1.2798
Epoch 7/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 9s 182ms/step - accuracy: 0.5964 - loss: 1.2680 - val_accuracy: 0.6240 - val_loss: 1.1537
Epoch 8/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 10s 177ms/step - accuracy: 0.5927 - loss: 1.2669 - val_accuracy